[package]
name = "thespian_macro"
version = "0.1.0"
authors = ["David Kern <david@mju.io>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
